resume: files/CV - James Fraser (2012).pdf
linkedin: http://www.linkedin.com/in/jamesfraser2
github: https://github.com/wulfgarpro
twitter: https://twitter.com/wulfgarpro
googleplus: https://plus.google.com/u/0/112088345124494773545/
jekyll: http://jekyllrb.com/
