baseurl: /
#destination: _site

site: https://wulfgarpro.github.io/
resume: files/JamesFraser-CV-2013.pdf
linkedin: http://www.linkedin.com/in/james-fraser
github: https://github.com/wulfgarpro
twitter: https://twitter.com/wulfgarpro
googleplus: https://plus.google.com/u/0/+JamesFraser_wulfgarpro/about
jekyll: http://jekyllrb.com/
blog: index.html
about: about.html
email: wulfgar.pro@gmail.com

#ftp_host: users.on.net
# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null
